CREATE DATABASE Company;
USE Company;
CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) PRIMARY KEY,
    NAME VARCHAR(20),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE DECIMAL(8,0),
    STATE VARCHAR(15),
    BALDUE DECIMAL(10,2)
);
RENAME TABLE CLIENT_MASTER TO CLIENT_DETAILS;
ALTER TABLE CLIENT_DETAILS
ADD PHONE VARCHAR(50) AFTER NAME;
ALTER TABLE CLIENT_DETAILS
MODIFY NAME VARCHAR(20) NOT NULL
COMMENT 'CLIENT NAME';
TRUNCATE TABLE CLIENT_DETAILS;
DROP TABLE CLIENT_DETAILS;
SELECT*FROM CLIENT_DETAILS;
SHOW TABLES;